"""Deterministic fake design provider (phase-16).

Two jobs: it lets the design stage run end-to-end before any MCP integration exists, and it is the
offline dev/demo fallback. Deterministic by construction — the same input always yields the same
``external_ref`` and markup — so tests can assert on exact output.
"""

from __future__ import annotations

import hashlib

from app.design.base import (
    DesignCapabilities,
    DesignCode,
    DesignImage,
    DesignResult,
    ProviderHealth,
    provider_error,
)

PROVIDER_KEY = "fake"

_CSS = """\
:root { color-scheme: dark; }
body { margin: 0; font-family: ui-sans-serif, system-ui, sans-serif;
       background: #0f172a; color: #e2e8f0; }
.wrap { max-width: 48rem; margin: 0 auto; padding: 3rem 1.5rem; }
h1 { font-size: 1.875rem; margin: 0 0 .5rem; }
.note { color: #94a3b8; }
.card { border: 1px solid #1e293b; border-radius: .75rem; padding: 1rem; margin-top: 1.5rem; }
"""


def _digest(*parts: str) -> str:
    joined = "\x1f".join(parts).encode("utf-8")  # unit separator: unambiguous
    return hashlib.sha256(joined).hexdigest()[:16]


def _html(title: str, body: str) -> str:
    return (
        "<!doctype html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8" />\n'
        f"<title>{title}</title>\n"
        '<link rel="stylesheet" href="design.css" />\n'
        "</head>\n<body>\n"
        '<div class="wrap">\n'
        f"<h1>{title}</h1>\n"
        f'<p class="note">{body}</p>\n'
        '<div class="card">Generated by the fake design provider.</div>\n'
        "</div>\n</body>\n</html>\n"
    )


class FakeDesignProvider:
    """Canned, deterministic designs. Keeps generated refs in memory for fetch/refine."""

    key = PROVIDER_KEY

    def __init__(self) -> None:
        self._designs: dict[str, DesignResult] = {}

    def _remember(self, result: DesignResult) -> DesignResult:
        self._designs[result.external_ref] = result
        return result

    def _is_own_ref(self, design_ref: str) -> bool:
        """Whether this ref was minted by *this* provider (so it survives a process restart)."""
        return design_ref.startswith(("fake-text-", "fake-image-"))

    async def generate_from_text(
        self,
        prompt: str,
        *,
        workspace: str | None = None,
        workspace_title: str | None = None,
    ) -> DesignResult:
        ref = f"fake-text-{_digest(prompt)}"
        return self._remember(
            DesignResult(
                provider=self.key,
                external_ref=ref,
                html=_html("Fake design", f"From prompt: {prompt}"),
                css=_CSS,
                preview_image=None,
                meta={"source": "text", "prompt": prompt},
            )
        )

    async def generate_from_image(
        self,
        images: list[DesignImage],
        prompt: str | None = None,
        *,
        workspace: str | None = None,
        workspace_title: str | None = None,
    ) -> DesignResult:
        if not images:
            raise provider_error(self.key, "At least one image is required")
        # Hash the bytes so identical screenshots produce an identical ref.
        fingerprint = _digest(*(hashlib.sha256(i.data).hexdigest() for i in images), prompt or "")
        ref = f"fake-image-{fingerprint}"
        names = ", ".join(i.filename for i in images)
        return self._remember(
            DesignResult(
                provider=self.key,
                external_ref=ref,
                html=_html("Fake design", f"From {len(images)} image(s): {names}"),
                css=_CSS,
                preview_image=None,
                meta={"source": "image", "images": [i.filename for i in images], "prompt": prompt},
            )
        )

    async def refine(self, design_ref: str, instruction: str) -> DesignResult:
        # The in-memory map is a cache, not the source of truth: a ref this provider *issued*
        # stays refinable across a control-plane restart (the design itself is persisted as an
        # artifact). Only a ref that was never ours is an error.
        if design_ref not in self._designs and not self._is_own_ref(design_ref):
            raise provider_error(self.key, f"Unknown design ref: {design_ref}")
        ref = f"{design_ref}-r{_digest(design_ref, instruction)}"
        return self._remember(
            DesignResult(
                provider=self.key,
                external_ref=ref,
                # Echo the instruction so refinement is observable in the output.
                html=_html("Fake design (refined)", f"Refined: {instruction}"),
                css=_CSS,
                preview_image=None,
                meta={"source": "refine", "refined_from": design_ref, "instruction": instruction},
            )
        )

    async def fetch_code(self, design_ref: str) -> DesignCode:
        design = self._designs.get(design_ref)
        if design is None:
            raise provider_error(self.key, f"Unknown design ref: {design_ref}")
        return DesignCode(html=design.html, css=design.css, assets={})

    def capabilities(self) -> DesignCapabilities:
        return DesignCapabilities(
            provider=self.key,
            from_image=True,
            from_text=True,
            refine=True,
            fetch_code=True,
            max_images=8,
        )

    async def health(self) -> ProviderHealth:
        return ProviderHealth.ok  # in-process: never down
